### ISSUE TITLE
How to develop for Tiddlydrive?

### ISSUE THREAD

**Issue by aneuhold** [tiddlydrive/development#7]
Hello!

How do you develop for Tiddlydrive? It looks like there are two repos. This one here is for development. But how do you point a google drive document towards a locally running TiddlyDrive website? 

Thanks for any help!

**Comment by LordRatte** [comment]
All the code runs in your browser with JavaScript. The code in your browser uses Google Drive's API to fetch the file and save it back. If you run a local instance, you need to set up a Google Console project with the Drive API activated and that has a key with your local domain allowed.
